/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\models\670c1a0b1298836a25015bab.glb -o src/components/Avatar.jsx -r public 
*/

import React, { useEffect, useMemo, useRef, useState } from 'react'
import { Euler, ExtendedColors, Layers, Matrix4, NodeProps, NonFunctionKeys, Overwrite, Quaternion, useFrame, useGraph, useLoader, Vector3 } from '@react-three/fiber'
import { useFBX, useAnimations, useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useControls } from 'leva'

import * as THREE from "three";
import { EventHandlers } from '@react-three/fiber/dist/declarations/src/core/events'
import { JSX } from 'react/jsx-runtime'
import { Group } from 'three'

const corresponding: Record<string, string> = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP"
};

export function Avatar(props: JSX.IntrinsicAttributes & Omit<ExtendedColors<Overwrite<Partial<THREE.Group<THREE.Object3DEventMap>>, NodeProps<THREE.Group<THREE.Object3DEventMap>, typeof THREE.Group>>>, NonFunctionKeys<{ position?: Vector3; up?: Vector3; scale?: Vector3; rotation?: Euler; matrix?: Matrix4; quaternion?: Quaternion; layers?: Layers; dispose?: (() => void) | null }>> & { position?: Vector3; up?: Vector3; scale?: Vector3; rotation?: Euler; matrix?: Matrix4; quaternion?: Quaternion; layers?: Layers; dispose?: (() => void) | null } & EventHandlers) {
  const { scene } = useGLTF('/models/670c1a0b1298836a25015bab.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  //const { nodes, materials } = useGraph(clone)
  const { nodes, materials } = useGraph(clone) as unknown as {
    nodes: {
      Wolf3D_Outfit_Top: THREE.SkinnedMesh;
      Wolf3D_Outfit_Bottom: THREE.SkinnedMesh;
      Wolf3D_Outfit_Footwear: THREE.SkinnedMesh;
      Wolf3D_Body: THREE.SkinnedMesh;
      EyeLeft: THREE.SkinnedMesh;
      EyeRight: THREE.SkinnedMesh;
      Wolf3D_Hair: THREE.SkinnedMesh;
      Hips: object
      Wolf3D_Teeth: THREE.SkinnedMesh;
      Wolf3D_Head: THREE.SkinnedMesh;
      // Add other node types as needed
    };
    materials: { [key: string]: THREE.Material };
  };

  const { playAudio, script } = useControls({
    playAudio: false,
    script: {
      value: "welcome",
      options: ["welcome", "pizzas"]
    },
  });

  const audio = useMemo(() => new Audio(`/audios/${script}.mp3`), [script]);
  const jsonFile = useLoader(THREE.FileLoader, `audios/${script}.json`) as string;
  const lipsync = JSON.parse(jsonFile);

  let blinkTime = 0;
  const blinkInterval = 2; // Blink every 2 seconds
  const speedBlink = 0.8;

  useFrame((_state, delta) => {
    blinkTime += delta;
    
    // When blinkTime reaches the blinkInterval (2 seconds)
    if (blinkTime >= blinkInterval) {
      blinkTime = 0;

      // Animate morph target to close eyes (eyesClosed)
      /*let eyesClosedVal = nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["eyesClosed"]];
      while (eyesClosedVal < 1) {
        eyesClosedVal += 0.2;
        nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["eyesClosed"]] = eyesClosedVal;
      }*/
      if (nodes.Wolf3D_Head.morphTargetInfluences && nodes.Wolf3D_Head.morphTargetDictionary) {
        const eyesClosedIndex = nodes.Wolf3D_Head.morphTargetDictionary["eyesClosed"];
        if (eyesClosedIndex !== undefined) {
          nodes.Wolf3D_Head.morphTargetInfluences[eyesClosedIndex] = THREE.MathUtils.lerp(
            nodes.Wolf3D_Head.morphTargetInfluences[eyesClosedIndex] || 0,
            1,
            speedBlink
          );
        }
      }

      setTimeout(() => {
        /*while (eyesClosedVal > 0) {
          eyesClosedVal -= 0.2;
          nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["eyesClosed"]] = eyesClosedVal;
        }*/
        if (nodes.Wolf3D_Head.morphTargetInfluences && nodes.Wolf3D_Head.morphTargetDictionary) {
          const eyesClosedIndex = nodes.Wolf3D_Head.morphTargetDictionary["eyesClosed"];
          if (eyesClosedIndex !== undefined) {
            nodes.Wolf3D_Head.morphTargetInfluences[eyesClosedIndex] = THREE.MathUtils.lerp(
              nodes.Wolf3D_Head.morphTargetInfluences[eyesClosedIndex] || 0,
              0,
              speedBlink
            );
          }
        }
      }, 100); // This duration defines how long the blink lasts
    }

  });

  useFrame(() => {
    const currentAudioTime = audio.currentTime;

    if (audio.paused || audio.ended) {
      setAnimation("Idle");
    }
    Object.values(corresponding).forEach((value) => {
      if (nodes.Wolf3D_Head.morphTargetInfluences && nodes.Wolf3D_Head.morphTargetDictionary) {
        const headIndex = nodes.Wolf3D_Head.morphTargetDictionary[value];
        if (headIndex !== undefined) {
          nodes.Wolf3D_Head.morphTargetInfluences[headIndex] = 0;
        }
      }
      if (nodes.Wolf3D_Teeth?.morphTargetInfluences && nodes.Wolf3D_Teeth?.morphTargetDictionary) {
        const teethIndex = nodes.Wolf3D_Teeth.morphTargetDictionary[value];
        if (teethIndex !== undefined) {
          nodes.Wolf3D_Teeth.morphTargetInfluences[teethIndex] = 0;
        }
      }
    });

    //console.log(nodes.EyeLeft.morphTargetDictionary);
    // console.log(nodes.Wolf3D_Head.morphTargetDictionary);

    // nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["eyesClosed"]] = 1;
    // nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["eyesLookDown"]] = 1;

    // nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["mouthSmile"]] = 1;
    // nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["mouthOpen"]] = 1;

    /*let eyesClosedVal = nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["eyesClosed"]];
    console.log(eyesClosedVal);

    while (eyesClosedVal < 1) {
      eyesClosedVal += 0.2;
      nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["eyesClosed"]] = eyesClosedVal;
    }

    console.log(eyesClosedVal);

    while (eyesClosedVal > 0) {
      eyesClosedVal -= 0.2;
      nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["eyesClosed"]] = eyesClosedVal;
    }
     
    nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["eyesLookDown"]] = 0;
    nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary["eyesLookUp"]] = 0;*/

    for (let i = 0; i < lipsync.mouthCues.length; i++) {
      const mouthCue = lipsync.mouthCues[i];
      if (currentAudioTime >= mouthCue.start && currentAudioTime <= mouthCue.end) {
        // console.log(mouthCure.value);
        /*nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary[corresponding[mouthCue.value]]] = 1;
        nodes.Wolf3D_Teeth.morphTargetInfluences[nodes.Wolf3D_Teeth.morphTargetDictionary[corresponding[mouthCue.value]]] = 1;*/
        /*let val = 0;
        let valStep = 0.2;
        val += valStep;
        while(val < 1) {
          nodes.Wolf3D_Head.morphTargetInfluences[nodes.Wolf3D_Head.morphTargetDictionary[corresponding[mouthCue.value]]] = val;
          nodes.Wolf3D_Teeth.morphTargetInfluences[nodes.Wolf3D_Teeth.morphTargetDictionary[corresponding[mouthCue.value]]] = val;
          val += valStep;
        }*/
          const speed = 0.5;
          if (nodes.Wolf3D_Head.morphTargetInfluences && nodes.Wolf3D_Head.morphTargetDictionary) {
            const index = nodes.Wolf3D_Head.morphTargetDictionary[corresponding[mouthCue.value]];
            if (index !== undefined) {
              nodes.Wolf3D_Head.morphTargetInfluences[index] = THREE.MathUtils.lerp(
                nodes.Wolf3D_Head.morphTargetInfluences[index] || 0,
                1,
                speed
              );
            }
          }
          if (nodes.Wolf3D_Teeth.morphTargetInfluences && nodes.Wolf3D_Teeth.morphTargetDictionary) {
            const index = nodes.Wolf3D_Teeth.morphTargetDictionary[corresponding[mouthCue.value]];
            if (index !== undefined) {
              nodes.Wolf3D_Teeth.morphTargetInfluences[index] = THREE.MathUtils.lerp(
                nodes.Wolf3D_Teeth.morphTargetInfluences[index] || 0,
                1,
                speed
              );
            }
        }
        
        break;
      }
    }
  });

  useEffect(() => {
    if (playAudio) {
      audio.play();
      if (script == "welcome") {
        setAnimation("Greeting");
      }
      else {
        setAnimation("Angry");
      }
    }
    else {
      setAnimation("Idle");
      audio.pause();
    }
  }, [playAudio, script]);

  const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
  const { animations: angryAnimation } = useFBX("/animations/Angry Gesture.fbx");
  const { animations: greetingAnimation } = useFBX("/animations/Standing Greeting.fbx");

  idleAnimation[0].name = "Idle";
  angryAnimation[0].name = "Angry";
  greetingAnimation[0].name = "Greeting";

  const [animation, setAnimation] = useState("Idle");

  const group = useRef<Group>(null);
  
  const { actions } = useAnimations([idleAnimation[0], angryAnimation[0], greetingAnimation[0]], group);

  useEffect(() => {
    if (actions[animation]) {
      actions[animation]?.reset().fadeIn(0.5).play();
      return () => {
        actions[animation]?.fadeOut(0.5);
      };
    }
  }, [animation, actions]);

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/models/670c1a0b1298836a25015bab.glb')
