/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\models\670c1a0b1298836a25015bab.glb -o src/components/Avatar.jsx -r public 
*/

import { useEffect, useRef, useState } from 'react'
import { useAnimations, useGLTF } from '@react-three/drei'
import { button, useControls } from 'leva'

import * as THREE from "three";
import { JSX } from 'react/jsx-runtime'
import { useChat } from "../hooks/useChat";
import { Lipsync } from '@/models/message';
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber';

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.20,
    mouthFunnel: 0.2,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 1,
    jawForward: 1,
    noseSneerLeft: 0.56,
    noseSneerRight: 0.50,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.69,
    mouthDimpleLeft: 0.25,
    mouthDimpleRight: 0.15,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.59,
    mouthSmileRight: 0.59,
    tongueOut: 0.93,
  },
};

const corresponding: Record<string, string> = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP"
};

let setupMode = false;

type GLTFResult = GLTF & {
  nodes: {
    Wolf3D_Hair: THREE.SkinnedMesh
    Wolf3D_Outfit_Top: THREE.SkinnedMesh
    Wolf3D_Outfit_Bottom: THREE.SkinnedMesh
    Wolf3D_Outfit_Footwear: THREE.SkinnedMesh
    Wolf3D_Body: THREE.SkinnedMesh
    EyeLeft: THREE.SkinnedMesh
    EyeRight: THREE.SkinnedMesh
    Wolf3D_Head: THREE.SkinnedMesh
    Wolf3D_Teeth: THREE.SkinnedMesh
    Hips: THREE.Bone
  }
  materials: {
    Wolf3D_Hair: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Top: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Bottom: THREE.MeshStandardMaterial
    Wolf3D_Outfit_Footwear: THREE.MeshStandardMaterial
    Wolf3D_Body: THREE.MeshStandardMaterial
    Wolf3D_Eye: THREE.MeshStandardMaterial
    Wolf3D_Skin: THREE.MeshStandardMaterial
    Wolf3D_Teeth: THREE.MeshStandardMaterial
  }
}

export function Avatar(props: JSX.IntrinsicElements['group']) {
    /*const { scene } = useGLTF('/models/670c1a0b1298836a25015bab-transformed.glb')
    const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes, materials } = useGraph(clone) as GLTFResult*/

    const { nodes, materials, scene } = useGLTF(
      "/models/670c1a0b1298836a25015bab-transformed.glb"
    ) as GLTFResult;

    const { message, onMessagePlayed, chat } = useChat();
  
    const [lipsync, setLipsync] = useState<Lipsync>();
  
    useEffect(() => {
      console.log(message);
      if (!message) {
        setAnimation("Idle");
        return;
      }
      setAnimation(message.animation);
      setFacialExpression(message.facialExpression);
      setLipsync(message.lipsync);
      const audio = new Audio("data:audio/mp3;base64," + message.audio);
      audio.play();
      setAudio(audio);
      audio.onended = onMessagePlayed;
    }, [message]);
  
    //const { animations } = useGLTF("/models/animations.glb");

    /*const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
    idleAnimation[0].name = "Idle";

    const { animations: sadIdleAnimation } = useFBX("/animations/Sad Idle.fbx");
    sadIdleAnimation[0].name = "Sad";

    const { animations: angryGestureAnimation } = useFBX("/animations/Angry Gesture.fbx");
    angryGestureAnimation[0].name = "Angry_1";

    const { animations: angryAnimation } = useFBX("/animations/Angry.fbx");
    angryAnimation[0].name = "Angry_2";

    const { animations: cryingAnimation } = useFBX("/animations/Crying.fbx");
    cryingAnimation[0].name = "Crying";

    const { animations: prayingAnimation } = useFBX("/animations/Praying.fbx");
    prayingAnimation[0].name = "Praying";

    const { animations: laughingAnimation } = useFBX("/animations/Laughing.fbx");
    laughingAnimation[0].name = "Laughing";

    const { animations: talking1Animation } = useFBX("/animations/Talking_1.fbx");
    talking1Animation[0].name = "Talking_1";

    const { animations: talking2Animation } = useFBX("/animations/Talking_2.fbx");
    talking2Animation[0].name = "Talking_2";

    const { animations: terrifiedAnimation } = useFBX("/animations/Terrified.fbx");
    terrifiedAnimation[0].name = "Terrified";
    
    const { animations: defeatedAnimation } = useFBX("/animations/Defeated.fbx");
    defeatedAnimation[0].name = "Defeated";

    const { animations: rumbaDancingAnimation } = useFBX("/animations/Rumba Dancing.fbx");
    rumbaDancingAnimation[0].name = "Rumba_Dancing";

    const { animations: twerkDancingAnimation } = useFBX("/animations/Dancing Twerk.fbx");
    twerkDancingAnimation[0].name = "Twerk_Dancing";

    const { animations: sillyDancingAnimation } = useFBX("/animations/Silly Dancing.fbx");
    sillyDancingAnimation[0].name = "Silly_Dancing";

    const { animations: standingGreetingAnimation } = useFBX("/animations/Standing Greeting.fbx");
    standingGreetingAnimation[0].name = "Standing_Greeting";*/

    //const animations = [idleAnimation[0], sadIdleAnimation[0], angryGestureAnimation[0], angryAnimation[0], cryingAnimation[0], prayingAnimation[0], laughingAnimation[0], talking1Animation[0], talking2Animation[0], terrifiedAnimation[0], defeatedAnimation[0], rumbaDancingAnimation[0], twerkDancingAnimation[0], sillyDancingAnimation[0], standingGreetingAnimation[0]];

    //const animations = [idleAnimation[0], sadIdleAnimation[0]];

    //const animations = [sadIdleAnimation[0]];

    //const animations = [idleAnimation[0]];

    //const animations = [rumbaDancingAnimation[0]];

    //const animations = [rumbaDancingAnimation[0], sadIdleAnimation[0]];

    //const animations = [idleAnimation[0], angryGestureAnimation[0]];

    //const animations = [idleAnimation[0], talking1Animation[0], talking2Animation[0]];

    const { animations } = useGLTF("/models/animations.glb");

    const group = useRef<THREE.Group>(null);
    const { actions, mixer } = useAnimations(animations, group);
    const [animation, setAnimation] = useState(
      animations.find((a) => a.name === "Idle") ? "Idle" : animations[0].name // Check if Idle animation exists otherwise use first animation
    );

    useEffect(() => {
      actions[animation]
        ?.reset()
        ?.fadeIn((mixer.getRoot() as THREE.AnimationObjectGroup)?.stats?.objects?.inUse == 0 ? 0 : 0.5)
        ?.play();
      return () => {
        actions[animation]?.fadeOut(0.5);
      };
    }, [animation]);

    const lerpMorphTarget = (target: string, value: number, speed = 0.1) => {
      scene.traverse((child) => {
        if (child instanceof THREE.SkinnedMesh && child.morphTargetDictionary) {
          const index = child.morphTargetDictionary[target];
          if (index === undefined || !child.morphTargetInfluences) {
            return;
          }
          const influence = child.morphTargetInfluences[index];
          if (influence === undefined) {
            return;
          }
          child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
            child.morphTargetInfluences[index],
            value,
            speed
          );
  
          if (!setupMode) {
            try {
              set({
                [target]: value,
              });
            } catch (error) {
              console.error("Error setting morph target:", error);
            }
          }
        }
      });
    };
  
    const [blink, setBlink] = useState(false);
    const [winkLeft, setWinkLeft] = useState(false);
    const [winkRight, setWinkRight] = useState(false);
    const [facialExpression, setFacialExpression] = useState("");
    const [audio, setAudio] = useState<HTMLAudioElement>();

    useFrame(() => {
      if (!setupMode) {
        Object.keys(nodes.EyeLeft.morphTargetDictionary as Record<string, number>).forEach((key) => {
          const mapping = facialExpressions[facialExpression as keyof typeof facialExpressions];
          if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
            return; // eyes wink/blink are handled separately
          }
          if (mapping && (mapping as Record<string, number>)[key]) {
            lerpMorphTarget(key, (mapping as Record<string, number>)[key], 0.1);
          } else {
            lerpMorphTarget(key, 0, 0.1);
          }
        });
      }
  
      lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
      lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);
      
      // LIPSYNC
      if (setupMode) {
        return;
      }
  
      const appliedMorphTargets: string[] = [];
      if (message && lipsync && audio && 'currentTime' in audio) {
        const currentAudioTime = audio.currentTime;

        for (let i = 0; i < lipsync.mouthCues.length; i++) {
          const mouthCue = lipsync.mouthCues[i];
          if (
          currentAudioTime >= mouthCue.start &&
          currentAudioTime <= mouthCue.end
          ) {
            appliedMorphTargets.push(corresponding[mouthCue.value]);
            lerpMorphTarget(corresponding[mouthCue.value], 1, 0.2);
            break;
          }
        }
      }

      Object.values(corresponding).forEach((value) => {
        if (appliedMorphTargets.includes(value)) {
          return;
        }
        lerpMorphTarget(value, 0, 0.1);
      });
    });
  
    useControls("FacialExpressions", {
      chat: button(() => chat),
      winkLeft: button(() => {
        setWinkLeft(true);
        setTimeout(() => setWinkLeft(false), 300);
      }),
      winkRight: button(() => {
        setWinkRight(true);
        setTimeout(() => setWinkRight(false), 300);
      }),
      animation: {
        value: animation,
        options: animations.map((a) => a.name),
        onChange: (value) => setAnimation(value),
      },
      facialExpression: {
        options: Object.keys(facialExpressions),
        onChange: (value) => setFacialExpression(value),
      },
      enableSetupMode: button(() => {
        setupMode = true;
      }),
      disableSetupMode: button(() => {
        setupMode = false;
      }),
      logMorphTargetValues: button(() => {
        const emotionValues: Record<string, number> = {};
        const morphDict = nodes.EyeLeft.morphTargetDictionary;
        if (morphDict) {
          Object.keys(morphDict).forEach((key) => {
            if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
              return; // eyes wink/blink are handled separately
            }
            const value =
              nodes.EyeLeft.morphTargetInfluences?.[
                nodes.EyeLeft.morphTargetDictionary?.[key] ?? -1
              ] ?? 0;
            if (value > 0.01) {
              emotionValues[key] = value;
            }
          });
        }
        console.log(JSON.stringify(emotionValues, null, 2));
      }),
    });
  
    const [, set] = useControls("MorphTarget", () =>
      Object.assign(
        {},
        ...Object.keys(nodes.EyeLeft.morphTargetDictionary ?? {}).map((key) => {
          return {
            [key]: {
              label: key,
              value: 0,
              min: nodes.EyeLeft.morphTargetInfluences?.[
                nodes.EyeLeft.morphTargetDictionary?.[key] ?? 0
              ] ?? 0,
              max: 1,
              onChange: (val: number) => {
                if (setupMode) {
                  lerpMorphTarget(key, val, 1);
                }
              },
            },
          };
        })
      )
    );
  
    useEffect(() => {
      let blinkTimeout: NodeJS.Timeout;
      const nextBlink = () => {
        blinkTimeout = setTimeout(() => {
          setBlink(true);
          setTimeout(() => {
            setBlink(false);
            nextBlink();
          }, 200);
        }, THREE.MathUtils.randInt(1000, 5000));
      };
      nextBlink();
      return () => clearTimeout(blinkTimeout);
    }, []);

    return (
      <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Hair"
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
    )
}

useGLTF.preload('/models/670c1a0b1298836a25015bab-transformed.glb')
useGLTF.preload("/models/animations.glb");





